#!/bin/bash
#SBATCH -J dipeptides      ## Name of job, you can define it to be any word
#SBATCH -A ACF-UTK0011	   ##Information about the project account to be charged
#SBATCH --nodes=1              ## Number of nodes
#SBATCH --ntasks-per-node=32  
#SBATCH --time=24:00:00
#SBATCH --partition=campus     
#SBATCH -e myjob.e%j	       ## Errors will be written in this file 
#SBATCH -o myjob.o%j           ## output of the run will be written here
#SBATCH --qos=campus


export PARA_ARCH=SMP
export PATH=$TURBODIR/bin/`sysname`:$PATH
export PARNODES=32

jobex -c 1000 > jobex.out
t2x -c > final.xyz
